### ISSUE TITLE
关于代理请求的问题

### ISSUE THREAD

**Issue by lisleyang** [RalfZhang/vue-douban#10]
在文中提到了通过设置proxy代理请求，避免跨域的问题；
想问下这种方法是否可以在正式项目中使用，在服务器上又该怎么部署呢？

**Comment by RalfZhang** [comment]
你是指 proxyTable 吗？这个只是开发时使用的请求转发方法，build 后只生成 html / js / css 文件，没有服务端的东西。
文末我提到了用 nginx 转发请求的方法，可以用于正式项目中。
当然，你也可以使用其他转发请求的方法。

**Comment by lisleyang** [comment]
好的 谢谢
