### ISSUE TITLE
Search text box overflows topbar

### ISSUE THREAD

**Issue by cuter44** [RalfZhang/vue-douban#2]
![photo_2017-03-13_16-10-40](https://cloud.githubusercontent.com/assets/2285039/23846530/da5087e0-0808-11e7-9191-d28fad113bda.jpg)

**Comment by RalfZhang** [comment]
Could you tell me which browser you are using?

**Comment by cuter44** [comment]
Firefox DEV desktop:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0

Android embeded return a mixed UA:
Mozilla/5.0 (Linux; U; Android 5.0.2; en-us; MI 2S Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 XiaoMi/MiuiBrowser/2.1.1

**Comment by linxq** [comment]
我下载之后  直接安装 部署 之后  解析不了vue文件  求解

**Comment by RalfZhang** [comment]
@linxq 请开新的 issue 提问，并附上详细报错内容。
