### ISSUE TITLE
关于代理设置问题

### ISSUE THREAD

**Issue by xumengzi** [RalfZhang/vue-douban#5]
首先感谢你的demo，按照你的博客写的代理，本地构建的时候和你展示的效果一样，用localhost可以访问到api里面的数据。
最后build的时候，发现豆瓣电影的api接口404了，但是我觉得和你设置的基本上是一样的额。
求大神告知如何解决问题！？
[这里是链接：](http://xumengzi.top/myProject/vue-movie/index.html#/)

**Comment by RalfZhang** [comment]
nginx 的配置我看看？应该是转发路径不对吧

**Comment by xumengzi** [comment]
没有什么Nginx，就是build之后把代码复制到了服务器（阿里云的服务器）。
如果要用Nginx，要怎么用呢？

**Comment by RalfZhang** [comment]
豆瓣不允许你跨域请求豆瓣的服务器，所以你需要在服务器使用 nginx 转发你的请求到豆瓣，详见这里  
https://github.com/RalfZhang/Vdo/blob/master/README.md#附配置与开启-nginx
