### ISSUE TITLE
网站无法访问了

### ISSUE THREAD

**Issue by superman66** [RalfZhang/vue-douban#7]
console 报错信息如下：
```
Uncaught SyntaxError: Unexpected token <
Uncaught SyntaxError: Unexpected token <
Uncaught ReferenceError: webpackJsonp is not defined
```

**Comment by RalfZhang** [comment]
看起来解决了，你看没问题就关闭 issue 咯

**Comment by superman66** [comment]
![image](https://cloud.githubusercontent.com/assets/12592949/24784473/70c7f318-1b85-11e7-96d9-d6c3acd9f0d6.png)
详情页面也报错了

**Comment by RalfZhang** [comment]
多谢检查，已解决问题。
（才发现是 vue2.x-douban 作者！仰慕！

**Comment by superman66** [comment]
哈哈哈，其实我是来参考你的UI界面设计的。

**Comment by RalfZhang** [comment]
哈哈，我的设计还有一些有待商榷的地方，更多可以参考 https://material.io/guidelines/

**Comment by superman66** [comment]
ok，有机会一起交流交流~
