### ISSUE TITLE
高度还原是怎么样做到的？

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [RalfZhang/vue-douban#8]
在首页下拉某一个位置，然后点击进入某一部电影详情，返回上一个页面还是原来的位置这是怎么样做到的，还有返回主页的的时候组件不会重新渲染我看了一下 <router-view></router-view>并没有加keepactive,这是怎么样回事？

**Comment by RalfZhang** [comment]
不太确定，我推测可能是因为同在一个 vue-router 下，会被记录成同一高度

**Comment by lisleyang** [comment]
本地存储吧，将列表和位置都存到localStorage里面

**Comment by RalfZhang** [comment]
@lisleyang 应该只是缓存到变量里，用本地存储不太可能：
1. 比起直接缓存到变量里，没有必要而且性能不好，  
2. 我打开看了一下，本地存储空空如也。
