### ISSUE TITLE
手机显示问题

### ISSUE THREAD

**Issue by yuyeqianxun** [RalfZhang/vue-douban#9]
![qq 20170412152817](https://cloud.githubusercontent.com/assets/17348438/24946186/a0db3836-1f94-11e7-8ae8-b53a130749cb.png)
手机：nubia Z11 mini；
浏览器：UC浏览器V11.4.9.941（最新版本，特意更新，之前的旧版也显示不正常）；
              QQ浏览器显示不正常；
              搜狗浏览器显示不正常；
百度浏览器和谷歌浏览器显示正常。

**Comment by RalfZhang** [comment]
放弃适配国产浏览器。
